name: test-library-on-nightly
description: Tests a library on a nightly
inputs:
  library-npm-package:
    description: The library npm package to add
    required: true
  platform:
    description: whether we want to build for iOS or Android
    required: true
runs:
  using: composite
  steps:
    - name: Create new app
      shell: bash
      run: |
        cd /tmp
        npx @react-native-community/cli init RNApp --skip-install --version nightly
    - name: Add library
      shell: bash
      run: |
        cd /tmp/RNApp
        yarn add ${{ inputs.library-npm-package }}

    # iOS
    - name: Setup xcode
      if: ${{ inputs.platform == 'ios' }}
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd
      with:
        xcode-version: '16.2.0'
    - name: Build iOS
      shell: bash
      if: ${{ inputs.platform == 'ios' }}
      run: |
        cd /tmp/RNApp/ios
        bundle install
        RCT_USE_RN_DEP=1 RCT_USE_PREBUILT_RNCORE=1 bundle exec pod install
        xcodebuild build \
          -workspace RNApp.xcworkspace \
          -scheme RNApp \
          -sdk iphonesimulator

    # Android
    - name: Setup Java for Android
      if: ${{ inputs.platform == 'android' }}
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Build Android
      shell: bash
      if: ${{ inputs.platform == 'android' }}
      run: |
        cd /tmp/RNApp/android
        ./gradlew assembleDebug
